### ISSUE TITLE
1. When possible: package software & use auto-containerization

### ISSUE THREAD

**Issue by mr-c** [ypriverol/containers-rules-manuscript#1]
Packaging options:
- (Bio)Conda
- Debian(Med)
- Brew

**Comment by mr-c** [comment]
Example: make Conda package and get a [biocontainers.pro](http://biocontainers.pro/) container for free.

Then you get to skip the rest of these rules as they come automatically!

**Comment by hmenager** [comment]
might seem obvious, but language-specific options like pypi, cpan, npm, etc.

**Comment by mr-c** [comment]
@hmenager Agreed, though I believe only conda is supported by biocontainers at this time

**Comment by osallou** [comment]
for automatic container creation , there is only conda at this time, via Dockerfile, would come soon, but no automatic metadata extraction

**Comment by ypriverol** [comment]
This is already included. Thanks for the suggestion.
