### ISSUE TITLE
Multi-stage builds

### ISSUE THREAD

**Issue by hroest** [ypriverol/containers-rules-manuscript#26]
I think that multi-stage builds [1] actually solve and make most of these recommendation redundant:
https://github.com/ypriverol/containers-rules-manuscript/blob/master/manuscript.adoc#6-reduce-the-size-of-your-container-as-much-as-possible

I consider some of these to be actually harmful, combining multiple RUN commands makes the files hard to read and debug. Since multi-stage builds are actually used to specifically address point 6, I think we should recommend them or at least add them to the list of suggestions

1. https://docs.docker.com/develop/develop-images/multistage-build/#name-your-build-stages

**Comment by ypriverol** [comment]
@hroest feel free to add that to the paper.

**Comment by ypriverol** [comment]
This has been added to the new version https://github.com/ypriverol/containers-rules-manuscript/blob/master/manuscript.adoc#52-write-optimized-dockerfiles

**Comment by hroest** [comment]
@ypriverol I dont think that is quite the same thing, multistage builds are the following:

```
FROM golang:1.7.3 as builder
WORKDIR /go/src/github.com/alexellis/href-counter/
RUN go get -d -v golang.org/x/net/html  
COPY app.go    .
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o app .

FROM alpine:latest  
RUN apk --no-cache add ca-certificates
WORKDIR /root/
COPY --from=builder /go/src/github.com/alexellis/href-counter/app .
CMD ["./app"]  
```


note how the most important part is the line `COPY --from=builder /go/src/github.com/alexellis/href-counter/app .` which copies data from the first image to the second. This also makes most recommendations under 5. obsolete as there is no more need to use a slim image for building etc

**Comment by hroest** [comment]
PS turns out the example is broken.

```
$ cat Dockerfile 

FROM golang:1.7.3 as builder
WORKDIR /go/src/github.com/alexellis/href-counter/
RUN wget https://raw.githubusercontent.com/go-training/helloworld/master/main.go  
RUN mv main.go app.go
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o app .

FROM alpine:latest  
RUN apk --no-cache add ca-certificates
WORKDIR /root/
COPY --from=builder /go/src/github.com/alexellis/href-counter/app .
CMD ["./app"]  
```

works and you can easily observe the differences in size: 6 MB vs 670 MB

```
$ sudo docker images | head -n 3
REPOSITORY                          TAG                 IMAGE ID            CREATED             SIZE
alpine_example_go                   latest              b808e290ad8d        3 minutes ago       6.23MB
builder_container                   latest              1a75035598fd        3 minutes ago       674MB
```
