### ISSUE TITLE
Docker base images should be versioned too

### ISSUE THREAD

**Issue by susheel** [ypriverol/containers-rules-manuscript#34]
Duplicate @bgruening's todo [manuscript.adoc#L130](https://github.com/ypriverol/containers-rules-manuscript/blame/master/manuscript.adoc#L130)

Need to update [manuscript.adoc#L134](https://github.com/ypriverol/containers-rules-manuscript/blame/master/manuscript.adoc#L134) too.

**Comment by susheel** [comment]
It is bad practice to build a container from the `latest` tag, as this may break subsequent builds of downstream containers.

The recommended practice for updating downstream containers is to always build from a versioned tag e.g. `FROM biocontainers/biocontainers:v1.0.0`

For downstream containers, updating the base image tag to later versions would require

- A manual version bump in the downstream Dockerfile
- Check for build errors
- Run any regression tests
- Push latest downstream container with it's own version bump

**Comment by ypriverol** [comment]
I agree. I have added that in the document example. This will trigger a discussion in Biocontainers recipes. Agree.
