### ISSUE TITLE
Suggestion to reorder recommendations

### ISSUE THREAD

**Issue by susheel** [ypriverol/containers-rules-manuscript#37]
Just an enhancement suggestion to reorder recommendations to support a logical flow of a typical Dockerfile. The idea would be to have a example (Box) for each recommendation and have a final example box that brings every recommendation together at the thirteenth recommendation **Provide reproducible builds**

New suggested order:

1. **Choose base image wisely**
`FROM biocontainers/biocontainers:v1.0.0`

2. **Tool and container versions should be explicit**
```
LABEL base_image="biocontainers:v1.0.0"
LABEL version="3"
LABEL software="Comet"
LABEL software.version="2016012"
```
3. **[Proposal]** Add appropriate `LABEL`s to point to software documentation, keywords and tags _(Can be merged in existing recommendations)_

```
LABEL about.summary="an open source tandem mass spectrometry sequence database search tool"
LABEL about.home="http://comet-ms.sourceforge.net"
LABEL about.documentation="http://comet-ms.sourceforge.net/parameters/parameters_2016010"
LABEL extra.identifiers.biotools="comet"
LABEL about.tags="Proteomics"
```

4. Check the license of the software _and add Maintainer information_
```
LABEL about.license_file="http://comet-ms.sourceforge.net"
LABEL about.license="SPDX:Apache-2.0"
LABEL maintainer="Felipe da Veiga Leprevost <felipe@leprevost.com.br>"
```

5. **[Proposal]** Use `ARG` for build-time and `ENV` for runtime evironment variables _(Can be merged in existing recommendations)_
```
ARG COMMET_VERSION="2016012"
ENV PATH /home/biodocker/bin/Comet:$PATH
```

6. **[Proposal]** Add explicit `WORKDIR` _(Can be merged in existing recommendations)_
```WORKDIR /data/```

7. **Reduce the size of your container as much as possible**
```
RUN ZIP=comet_binaries_${COMMET_VERSION}.zip && \
  wget https://github.com/BioDocker/software-archive/releases/download/Comet/$ZIP -O /tmp/$ZIP && \
  unzip /tmp/$ZIP -d /home/biodocker/bin/Comet/ && \
  chmod -R 755 /home/biodocker/bin/Comet/* && \
  rm /tmp/$ZIP
```
_Note the use of build time `ARG`s in the `RUN` process_ 

8. **Relevant tools and software should be executable and in the PATH**
```
RUN mv /home/biodocker/bin/Comet/comet_binaries_${COMMET_VERSION}/comet.${COMMET_VERSION}.linux.exe /home/biodocker/bin/Comet/comet
```

9. **Document the build files**
TODO: Mention the possibility of interspesing the Dockerfile with `#` comments

10. **Add functional testing logic**

11. **Avoid using `ENTRYPOINT`**

12. **Provide helpful usage message via `CMD`**

13. **Provide reproducible builds**

14. **Make your package or container discoverable**

**Comment by ypriverol** [comment]
@susheel Is more the current paper is more about containerization and not the technology. For that reason, we follow mainly a flow about how to create containers within current technologies from packaging to the final containers.

**Comment by susheel** [comment]
Many of the recommendations a tailored towards containers (6/11). It was just a suggestion so that there is a logical flow for someone reads them and views an example Dockerfile simultaneously.
