### ISSUE TITLE
Upload your container image to a public registry or collection

### ISSUE THREAD

**Issue by pditommaso** [ypriverol/containers-rules-manuscript#39]
A container should *always* distributed along with the Dockerfile/recipe used to create it, for transparency and documentation purpose. 

However the availability of the Dockerfile does not guarantee the *reproducibility* of the container images, and consequently, of the associated data-analyses. When re-creating a container image, one or more software packages can be not more available. 

To protect against software decay upload your container images to a public registry such as DockerHub or Quay. Even better, use community a collection such as BioContainers which manage the versioning and the long the archiving of container images.

**Comment by ypriverol** [comment]
@pditommaso we have a _findable_ recommendation (https://github.com/ypriverol/containers-rules-manuscript/blob/master/manuscript.adoc#9-make-your-package-or-container-discoverable). Can you comment in a PR this idea. Would be good to have your PR with ideas around both issues (this one and https://github.com/ypriverol/containers-rules-manuscript/issues/10)

**Comment by pditommaso** [comment]
I can do that. Is there a deadline for the ms submission ?

**Comment by ypriverol** [comment]
We would like to submit by Friday. ;)

**Comment by pditommaso** [comment]
Oops, I think I won't be able to work on that by Friday. Feel free to use my comments if you think are relevant/coherent with the ms.

**Comment by ypriverol** [comment]
I will leave this open. We can try to submit next week

**Comment by susheel** [comment]
I think this has been partly addressed in [Recommendation 9](https://github.com/ypriverol/containers-rules-manuscript/blob/master/manuscript.adoc#9-make-your-package-or-container-discoverable)

**Comment by hroest** [comment]
and [Recommendation 10](https://github.com/ypriverol/containers-rules-manuscript/blob/master/manuscript.adoc#10-provide-reproducible-builds) 

> However the availability of the Dockerfile does not guarantee the reproducibility of the container images, and consequently, of the associated data-analyses. When re-creating a container image, one or more software packages can be not more available.

I think the solution is not (at least not only) to distribute the container, but to make the Dockerfile reproducible. Again, one should avoid to use internal file servers, internal resources, resources on fragile infrastructure (self-hosted servers of the lab) etc. Only use third-party sites and official upstream distribution mechanisms, such as github to download code, making the container as much self-contained as possible. Again, we should look at what debian is doing, such as here: https://packages.debian.org/sid/libopenms2.0 where they host the actual src code, a set of instructions how to build the source code and patches and a signature. We should try and learn from these people that had to deal with the same issues before (e.g. vanishing resources, changing upstream, applying patches to upstream etc.).

**Comment by ypriverol** [comment]
I think this idea is now clear in both rule 10 and 9.

**Comment by hroest** [comment]
@ypriverol I agree, but in the long run I think we should learn from the debian people and we may need to even host the source code ourselves to make sure that we have an immutable, reproducible way of building the exact same container with the same source code. There is probably a reason that they do it this way -- they basically have the same problem as we do. The only way to solve it is to keep the source code and build instructions at the same place under your control.

**Comment by ypriverol** [comment]
We have started doing that in biocontainers. We have an ongoing project that backup/copy the tool source and binaries into an inhouse storage system. Will be out soon.

**Comment by bgruening** [comment]
> @ypriverol I agree, but in the long run I think we should learn from the debian people and we may need to even host the source code ourselves to make sure that we have an immutable, reproducible way of building the exact same container with the same source code. 

If we use the bioconda based containers we already do this. We store every artifact to build the containers. Please don't create a new system here.

**Comment by hroest** [comment]
> Please don't create a new system here.

no intention to do that, dont worry.
