### ISSUE TITLE
4. For permissions management, should be runnable as any user within the container, not just root

### ISSUE THREAD

**Issue by mr-c** [ypriverol/containers-rules-manuscript#4]

**Comment by prvst** [comment]
I'm not sure about this because the use we have inside the container is pre-set with some permissions on the base image.

**Comment by mr-c** [comment]
If this isn't done and files are written as the `root` user in external volumes then the user won't have the ability to delete or modify the outputs of the container.

**Comment by osallou** [comment]
@mr-c  docker does not let you run with "any" user, only user created in container, ie *root* and *biodocker* for biocontainers. This is the *docker* way. Generating output files will indeed generate results with a user id different from user executing the task. And you can't do automatic mapping with calling user id.

With singularity, it is different, as container will be executed with current user id (works in a different manner). This is true with a docker container used by singularity, whatever the USER directive in Dockerfile.

**Comment by osallou** [comment]
but this kind of user/file management and difference between docker/singularity could/should be explained.
