### ISSUE TITLE
Do not impose hard paths

### ISSUE THREAD

**Issue by pditommaso** [ypriverol/containers-rules-manuscript#40]
I would also add some notes to not impose the usage of hard path when using containerised software. I've seen a lot of people expecting data to be mapped to a specific directory in the container e.g. `/data` or `/inputs`. This is a bad practice because limits the portability of the container and it makes hard to re-use it. Along the same line it should be avoided the use of custom `WORKDIR` in the container definition. 

As general advice the container execution should be *transparent*, in the meaning the containers software should behave irrespective of the container usage, said in other term, the user should be able to use the containerised software independently the container usage.

**Comment by susheel** [comment]
I have seen some legacy tools that expect certain files/inputs in particular locations on the filesystem and I agree wholeheartedly that this should not be encouraged.

Would a recommendation (specifically for legacy support) exposing this a `VOLUME` mount point help? As this would enable the user/orchestrator to modify the mount point externally without impacting the expectation of the legacy software too much.

**Comment by hroest** [comment]
in addition to this, we should recommend to not create the folders `/data` and `/inputs` in the container as top-level directories as people will mount stuff on top of this and then hide whatever is in the container file system. Maybe we can recommend against creating these toplevel directories or just (i) against creating root-level directories in the first place and (ii) against mounting anything on root level but rather use `/mnt`

**Comment by ypriverol** [comment]
@hroest Actually we have recommended before /data as data folder for all biocontainers. This recommendation should be carefully taken. We did that to enable a common entry point for all data accessible for all users, especially for _biodocker_ user. I will try to avoid this recommendation for now and move this forward in BioContainers 2.0
