### ISSUE TITLE
Note about "One tool, one container" 

### ISSUE THREAD

**Issue by pditommaso** [ypriverol/containers-rules-manuscript#41]
Just some thoughts about the first point "One tool, one container". 

While this is a good practice to maximise the containers usability and makes perfect sense in some scenarios, like for example the BioContainers project, in other contexts it's a principle to abstract IMO. In real world applications it's need to compose many tools together, just think `bwa .. | samtools .. | etc`. 

In this scenario, having a a tool per container is a limiting factor that prevents that idiom or more in general the use of multiple tools in the same task.

**Comment by timosachsenberg** [comment]
Yes, I think it is about balancing reusability and ease of use. Maybe we should make a stronger point why we strongly recommend the one tool, one container philosophy (but maybe acknowledge use cases where a monolithic docker might be an advantage).

**Comment by susheel** [comment]
Yes, I agree. While "One tool, one container" is a good norm, we should also add the caveat to "use your best judgement to keep your containers as modular and scoped in functionality as possible".

You may use your judgement to compose a layered container based on other containerised tools. Here, we strongly recommend that the modular composition of these tools should also be exposed as a single modular tool - still abiding by "One Tool, One Container" guideline.

**Comment by ypriverol** [comment]
Feel free to add that idea into the paper.

**Comment by ypriverol** [comment]
@pditommaso @timosachsenberg @susheel Idea already added https://github.com/ypriverol/containers-rules-manuscript/blob/master/manuscript.adoc#2-one-tool-one-container . Please review the current version.

**Comment by bgruening** [comment]
@timosachsenberg if you can up with a nice sentence that would be great.
I find it really hard to formulate this in a nice way but still discourage devs to use it ;)

To just give an example why the above example is a bad one, if you assume that the `bwa=x.y` container contains samtools, but you have no handle with samtools your pipeline will most likely crash. As the syntax was samtools has changed in the past. That said we do support multi-package containers with the mulled-* one, that do not have this problem.
