### ISSUE TITLE
5. Eschew ENTRYPOINT

### ISSUE THREAD

**Issue by mr-c** [ypriverol/containers-rules-manuscript#5]

**Comment by ypriverol** [comment]
@mr-c Can you review the current version of the manuscript an include more information about this.

**Comment by rajido** [comment]
I did struggle with this recommendation. I think it just needs to rewrite the last two sentences.

**Comment by ypriverol** [comment]
@mr-c can you add some more point here? Can you also comment how this benefits for example CWL.

**Comment by ypriverol** [comment]
I will close this issue because is well reflected in the paper now.
