### ISSUE TITLE
Facetious Issue: GDPR Compliance

### ISSUE THREAD

**Issue by susheel** [ypriverol/containers-rules-manuscript#51]
Based on a recent EBI internal conversation about source code authorship in Git repositories - Is our recommendation to add the `maintainer` label compliant with the new GDPR regulations? Data that will be stored will be:
- Full name
- Email Address

More a question for the Bioinformatics container registries (bio.tools and biocontainers.pro)

It could be argued as a **legitimate interest** to ask for this information - for the sake of reproducibility, but will we need to comply with the **right to be forgotten** directive which would mean deleting all `maintainer` labels of the user even for downstream multi-stage builds.

I'm not assuming the **right to be forgotten** trumps **legitimate interest**, but do we have a legitimate reason for processing this information. We could argue "we could keep personal information indefinitely in the **public interest**. We would need to define why it is in the public interest.

**Comment by ypriverol** [comment]
@susheel, even when this is a great idea; I don't think is within the scope of this publication. We need to keep on eyes on this and probably for the BioContainers 2.0 paper define really what to do. This is not only involving Biocontainers but also BioConda and other communities. Also, our systems should be updated.

**Comment by susheel** [comment]
@ypriverol Sure. I'm just flagging it up for the communities to pick up. I
think may not be as relevant for this paper, but just to be aware that the
recommendation for having a `mainatiner` label will be discrepancy between
our recommendation and what the communities do for compliance at a later
date.

>

**Comment by bgruening** [comment]
@susheel would that not be a problem for github? We are not an institution, github is.

**Comment by ypriverol** [comment]
Well, I think is not even clear what will happen with the Journal papers, Github Code, etc. We are the Tail in a long chain.
